# Add the Stages for this pipeline

# Xamarin.Android

# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  droidOutputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)/Droid'
  iOSOutputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)/iOS'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(droidOutputDirectory)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(droidOutputDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'ProductionAndroid'
    appSlug: 'GuardianAngel360/GA360-APP.Android'
    appFile: '$(droidOutputdirectory)/com.guardianangel360.ga360.apk'
    buildVersion: '1'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Here they are'
    destinationType: 'groups'
    
#- task: AndroidSigning@3
#  inputs:
#    apksign: true
#    apkFiles: '**/*.apk'
#    apksignerKeystoreFile: 'GuardianAngel360.keystore'
#    apksignerKeystorePassword: 'AcatoIm2022!'
#    apksignerKeystoreAlias: 'GuardianAngel360'
#    zipalign: true
    
